sudo: required
services:
  - docker
language: java
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
    - ./mycache
before_install:
  - openssl aes-256-cbc -K $encrypted_c115264f075c_key -iv $encrypted_c115264f075c_iv -in com-alexvak-c352c0921585.json.enc -out com-alexvak-c352c0921585.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file com-alexvak-c352c0921585.json
  - gcloud config set project com-alexvak
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials alexvak-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

script:
  - mvn clean install
  - cp target/spring5-recipe-app-0.0.1-SNAPSHOT.jar ./mycache/app.jar

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master