spring:
  datasource:
    url: jdbc:mysql://recipe-mysql-cluster-ip-service:3306/recipe
    username: recipe
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false