apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: recipe-alexvak-com-tls
spec:
  secretName: recipe-alexvak-com
  issuerRef:
    name: recipe-letsencrypt-prod
    kind: ClusterIssuer
  commonName: recipe.alexvak.com
  dnsNames:
    - recipe.alexvak.com
    - www.recipe.alexvak.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - recipe.alexvak.com
          - www.recipe.alexvak.com