apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: recipe-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'avakarchuk@me.com'
    privateKeySecretRef:
      name: recipe-letsencrypt-prod
    http01: {}